[build]
  publish = "dist"
  command = "npm install && (npm run build || npm run build:simple)"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.20.7"
  NPM_VERSION = "9"

[build.processing]
  skip_processing = false

[context.production.environment]
  NODE_VERSION = "18.20.7"

[context.deploy-preview.environment]
  NODE_VERSION = "18.20.7"

[context.branch-deploy.environment]
  NODE_VERSION = "18.20.7"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
